[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/admin.html"
  [headers.values]
    Cache-Control = "no-store"


